import { useState } from 'react';
import { BadgeCheck, ChevronDown, ClipboardList, Info, ShieldAlert, TriangleAlert } from 'lucide-react';
import { number, percent, sourceColors, localizedMessage } from '../format';
import type { Calculation, Violation } from '../types';

const violationValue = (value: number | null, unit?: string) => value === null ? '—'
  : unit === 'share' ? percent(value, 2) : `${number(value, 2)}${unit === 't' ? ' т' : unit === 't/year' ? ' т/год' : unit === 'years' ? ' лет' : unit === 'million 2035 units' ? ' млн' : ''}`;

function DiagnosticTable({ items, warning = false }: { items: Violation[]; warning?: boolean }) {
  const label = warning ? 'Предупреждения об устойчивости' : 'Нарушения ограничений';
  return <div className="table-scroll" tabIndex={0} aria-label={label}><table className="violations-table"><caption className="sr-only">{label}: год, причина, фактическое значение и предел</caption><thead><tr><th>Год / канал</th><th>Причина</th><th>Факт</th><th>{warning ? 'Ориентир' : 'Предел'}</th></tr></thead><tbody>{items.map((item, index) => <tr key={`${item.code}-${index}`}><td>{item.year ?? 'Горизонт'}{item.source && <span className="violation-source">{item.source}</span>}</td><td><strong>{localizedMessage(item.message)}</strong><code>{item.code}</code></td><td className={warning ? 'text-warning' : 'text-danger'}>{violationValue(item.actual, item.unit)}</td><td>{violationValue(item.limit, item.unit)}</td></tr>)}</tbody></table></div>;
}

export default function ResultTables({ result, year }: { result: Calculation; year: number }) {
  const [tab, setTab] = useState<'annual' | 'contracts'>('annual');
  const attention = result.kpi_summary.has_shortage || result.warning_details.length > 0;
  return <>
    <section className="panel" id="balance"><div className="panel-heading"><div><p className="eyebrow"><ClipboardList size={13} /> Проверяемые данные</p><h2>Баланс и контракты</h2></div><span className="small-badge">{result.scenario === 'BASE' ? 'BASE' : 'STRESS'}{result.demand_profile !== 'BASE' ? ` · спрос ${result.demand_profile}` : ''}</span></div>
      <div className="table-tabs" role="group" aria-label="Таблица результатов"><button aria-pressed={tab === 'annual'} className={tab === 'annual' ? 'active' : ''} onClick={() => setTab('annual')}>Годовой баланс</button><button aria-pressed={tab === 'contracts'} className={tab === 'contracts' ? 'active' : ''} onClick={() => setTab('contracts')}>Поставки {year}</button></div>
      <div className="table-scroll" tabIndex={0} aria-label="Прокручиваемая таблица результатов">
        {tab === 'annual' ? <table><caption className="sr-only">Материальный и финансовый баланс по выбранному горизонту</caption><thead><tr><th>Год</th><th>Спрос, т</th><th>Приход, т</th><th>Потери, т</th><th>Выдано, т</th><th>Остаток, т</th><th>Дефицит, т</th><th>Сервис</th><th>Крит. сервис</th><th>Затраты, млн</th></tr></thead><tbody>{result.annual_balances.map((row) => <tr key={row.year} className={row.year === year ? 'selected-row' : ''}><th scope="row">{row.year}</th><td>{number(row.demand_total)}</td><td>{number(row.inflow)}</td><td>{number(row.losses)}</td><td>{number(row.served_total)}</td><td>{number(row.end_inventory)}</td><td className={row.has_shortage ? 'text-danger' : ''}>{number(row.shortage)}</td><td className={row.service_below_target ? 'text-danger' : ''}>{percent(row.service_level)}</td><td className={row.critical_service_below_target ? 'text-danger' : ''}>{percent(row.critical_service_level)}</td><td>{number(row.total_cost)}</td></tr>)}</tbody></table>
          : <table><caption className="sr-only">Контракты и первые даты поставок за {year} год</caption><thead><tr><th>Канал</th><th>Заказ, т</th><th>Факт, т</th><th>Бронь, т/год</th><th>Lead, дней</th><th>Первый заказ</th><th>Первая поставка</th><th>Закупки, млн</th></tr></thead><tbody>{result.source_schedule.filter((row) => row.year === year && row.kind !== 'startup').map((row) => <tr key={`${row.source_id}-${row.kind}`}><th scope="row"><i className="legend-dot" style={{ background: sourceColors[row.source_id] }} />{row.source_id} · {row.source_name}{row.kind === 'additional' ? ' · дозаказ' : ''}</th><td>{number(row.ordered_t)}</td><td>{number(row.delivered_t)}</td><td>{number(row.reserved_capacity_t_per_year)}</td><td>{row.lead_days}</td><td>{row.ordered_t > 0 ? row.first_order_date ?? '—' : '—'}</td><td>{row.delivered_t > 0 ? row.first_arrival_date ?? '—' : '—'}</td><td>{number(row.procurement)}</td></tr>)}</tbody></table>}
      </div><p className="table-footnote">Топливо — тонны. Деньги — млн условных единиц в постоянных ценах 2035 года. Начальный запас и его закупка учитываются отдельно.</p>
    </section>
    <section className="panel violations-panel" id="constraints"><div className="panel-heading"><div><p className="eyebrow"><ShieldAlert size={13} /> Контроль ограничений</p><h2>Диагностика плана</h2></div><span className={`status-pill ${!result.feasible ? 'danger' : attention ? 'warning' : 'good'}`}>{result.violation_details.length} нарушений · {result.warning_details.length} предупреждений</span></div>
      {result.violation_details.length === 0 ? <div className={`success-message ${attention ? 'text-warning' : ''}`}>{attention ? <TriangleAlert size={21} /> : <BadgeCheck size={21} />}<div><strong>{attention ? 'Ограничения выполнены, есть предупреждения' : 'Формальные ограничения выполнены'}</strong><p>Дефицит за весь горизонт: {number(result.kpi_summary.total_shortage, 2)} т.{result.scenario === 'MANDATORY_STRESS' ? ' В STRESS общий сервис ≥97% и критический ≥99% — ориентиры устойчивости.' : ''}</p></div></div>
        : <DiagnosticTable items={result.violation_details} />}
      {result.warning_details.length > 0 && <><p className="table-footnote text-warning">Предупреждения об устойчивости: сервис, дефицит и запас инвестиционного бюджета.</p><DiagnosticTable items={result.warning_details} warning /></>}
    </section>
    <section className="panel methodology" id="methodology"><details><summary><span><Info size={18} /> Методология и границы модели</span><ChevronDown size={17} /></summary><div className="methodology-grid">
      <div><h3>Временной и материальный баланс</h3><p>365 дней в году; месяц — 365/12 дней. Спрос и доступные поставки распределены равномерно по дням. Критический спрос обслуживается первым. Потери применяются один раз к валовому приходу.</p><p>Проверяется физический запас на начало года: не менее 45 дней спроса. Свободная аварийная мощность не считается запасом. Переполнение не скрывается обрезкой объёма.</p></div>
      <div><h3>Деньги, контракты, инвестиции</h3><p>Стоимость начального запаса включена в 2035. Учитываются Take-or-Pay, резервирование мощности, хранение, постоянный OPEX и CAPEX. Дисконтирование — к началу 2035; годовые затраты отнесены к началу года.</p><p>Оптимизатор меняет годовые заказы при фиксированных инвестициях, начальном запасе и явной брони. План проверяется суточным ядром. Оптимальность для других инвестиций не заявляется.</p><p>У C подготовка 18–24 месяца начинается после исполнения опциона. Срок текущей поставки задаётся отдельно: по умолчанию 4 месяца по допущению команды, с проверкой чувствительности в сравнении стратегий.</p></div>
      <div><h3>Стресс и риски</h3><p>Обязательный стресс включает рост спроса, цен A/B, срыв D и предел потерь 2%. Reliability повторно не уменьшает поставки. В STRESS сервис ниже 97% общего или 99% критического вызывает предупреждение об устойчивости.</p><p>LOW/HIGH берутся из исходных данных с сохранением критической доли каждого года и рассчитываются отдельно от STRESS. Риск-реестр и чувствительность доступны в аналитике. Вероятностная симуляция не выполняется.</p><p>Любой положительный годовой заказ Emergency считается использованием канала; третий год подряд запрещён — консервативное допущение команды. Все заказы размещаются заранее с учётом lead time; в отчёте реакции ранее размещённые годовые контракты сохраняются, а дозаказы прибывают не раньше даты решения плюс срок доставки. Основная реакция использует заранее обеспеченную мощность; доступность новых контрактов исследуется отдельно как допущение. Бронь и TOP сохраняются при сокращении заказа и не списываются дважды.</p></div>
    </div></details></section>
  </>;
}
