import { useState } from 'react';
import { BadgeCheck, ChevronDown, ClipboardList, Info, ShieldAlert } from 'lucide-react';
import { number, percent, sourceColors } from '../format';
import type { Calculation, Violation } from '../types';

const violationValue = (value: number | null, unit?: string) => value === null ? '—'
  : unit === 'share' ? percent(value, 2) : `${number(value, 2)}${unit === 't' ? ' т' : unit === 't/year' ? ' т/год' : unit === 'years' ? ' лет' : unit === 'million 2035 units' ? ' млн' : ''}`;

export default function ResultTables({ result, year }: { result: Calculation; year: number }) {
  const [tab, setTab] = useState<'annual' | 'contracts'>('annual');
  return <>
    <section className="panel" id="balance"><div className="panel-heading"><div><p className="eyebrow"><ClipboardList size={13} /> Проверяемые данные</p><h2>Баланс и контракты</h2></div><span className="small-badge">{result.scenario === 'BASE' ? 'BASE' : 'STRESS'}</span></div>
      <div className="table-tabs" role="group" aria-label="Таблица результатов"><button aria-pressed={tab === 'annual'} className={tab === 'annual' ? 'active' : ''} onClick={() => setTab('annual')}>Годовой баланс</button><button aria-pressed={tab === 'contracts'} className={tab === 'contracts' ? 'active' : ''} onClick={() => setTab('contracts')}>Поставки {year}</button></div>
      <div className="table-scroll" tabIndex={0} aria-label="Прокручиваемая таблица результатов">
        {tab === 'annual' ? <table><caption className="sr-only">Материальный и финансовый баланс с 2035 по 2040 год</caption><thead><tr><th>Год</th><th>Спрос, т</th><th>Приход, т</th><th>Потери, т</th><th>Выдано, т</th><th>Остаток, т</th><th>Дефицит, т</th><th>Сервис</th><th>Крит. сервис</th><th>Затраты, млн</th></tr></thead><tbody>{result.annual_balances.map((row) => <tr key={row.year} className={row.year === year ? 'selected-row' : ''}><th scope="row">{row.year}</th><td>{number(row.demand_total)}</td><td>{number(row.inflow)}</td><td>{number(row.losses)}</td><td>{number(row.served_total)}</td><td>{number(row.end_inventory)}</td><td className={row.shortage > 0.000001 ? 'text-danger' : ''}>{number(row.shortage)}</td><td>{percent(row.service_level)}</td><td>{percent(row.critical_service_level)}</td><td>{number(row.total_cost)}</td></tr>)}</tbody></table>
          : <table><caption className="sr-only">Контракты и первые даты поставок за {year} год</caption><thead><tr><th>Канал</th><th>Заказ, т</th><th>Факт, т</th><th>Бронь, т/год</th><th>Lead, дней</th><th>Первый заказ</th><th>Первая поставка</th><th>Закупки, млн</th></tr></thead><tbody>{result.source_schedule.filter((row) => row.year === year && row.kind === 'regular').map((row) => <tr key={row.source_id}><th scope="row"><i className="legend-dot" style={{ background: sourceColors[row.source_id] }} />{row.source_id} · {row.source_name}</th><td>{number(row.ordered_t)}</td><td>{number(row.delivered_t)}</td><td>{number(row.reserved_capacity_t_per_year)}</td><td>{row.lead_days}</td><td>{row.ordered_t > 0 ? row.first_order_date ?? '—' : '—'}</td><td>{row.delivered_t > 0 ? row.first_arrival_date ?? '—' : '—'}</td><td>{number(row.procurement)}</td></tr>)}</tbody></table>}
      </div><p className="table-footnote">Топливо — тонны. Деньги — млн условных единиц в постоянных ценах 2035 года. Начальный запас и его закупка учитываются отдельно.</p>
    </section>
    <section className="panel violations-panel" id="constraints"><div className="panel-heading"><div><p className="eyebrow"><ShieldAlert size={13} /> Контроль ограничений</p><h2>Диагностика плана</h2></div><span className={`status-pill ${result.feasible ? 'good' : 'danger'}`}>{result.violation_details.length} нарушений</span></div>
      {result.violation_details.length === 0 ? <div className="success-message"><BadgeCheck size={21} /><div><strong>Формальные ограничения выполнены</strong><p>Дефицит за весь горизонт: {number(result.kpi_summary.total_shortage, 2)} т.{result.scenario === 'MANDATORY_STRESS' ? ' В STRESS пороги сервиса BASE не применяются.' : ''}</p></div></div>
        : <div className="table-scroll" tabIndex={0} aria-label="Прокручиваемая таблица нарушений"><table className="violations-table"><caption className="sr-only">Причина, год, фактическое значение и предел каждого нарушения</caption><thead><tr><th>Год / канал</th><th>Причина</th><th>Факт</th><th>Предел</th></tr></thead><tbody>{result.violation_details.map((violation: Violation, index) => <tr key={`${violation.code}-${index}`}><td>{violation.year ?? 'Горизонт'}{violation.source && <span className="violation-source">{violation.source}</span>}</td><td><strong>{violation.message}</strong><code>{violation.code}</code></td><td className="text-danger">{violationValue(violation.actual, violation.unit)}</td><td>{violationValue(violation.limit, violation.unit)}</td></tr>)}</tbody></table></div>}
    </section>
    <section className="panel methodology" id="methodology"><details><summary><span><Info size={18} /> Методология и границы модели</span><ChevronDown size={17} /></summary><div className="methodology-grid">
      <div><h3>Временной и материальный баланс</h3><p>365 дней в году; месяц — 365/12 дней. Спрос и доступные поставки распределены равномерно по дням. Критический спрос обслуживается первым. Потери применяются один раз к валовому приходу.</p><p>Проверяется физический запас на начало года: не менее 45 дней спроса. Свободная аварийная мощность не считается запасом. Переполнение не скрывается обрезкой объёма.</p></div>
      <div><h3>Деньги, контракты, инвестиции</h3><p>Стоимость начального запаса включена в 2035. Учитываются Take-or-Pay, резервирование мощности, хранение, постоянный OPEX и CAPEX. Дисконтирование — к началу 2035; годовые затраты отнесены к началу года.</p><p>Оптимизатор меняет годовые заказы при фиксированных инвестициях, начальном запасе и явной брони. План проверяется суточным ядром. Оптимальность для других инвестиций не заявляется.</p></div>
      <div><h3>Стресс и риски</h3><p>Обязательный стресс включает рост спроса, цен A/B, срыв D и предел потерь 2%. Reliability повторно не уменьшает поставки. В STRESS сервис измеряется, но пороги BASE не добавляются к правилам организаторов.</p><p>Монте-Карло и FMEA в текущем расчёте не выполняются. Множители спроса и цен позволяют исследовать чувствительность без вероятностных утверждений.</p></div>
    </div></details></section>
  </>;
}
